### ISSUE TITLE
Consider a design similar to Chrome's MiraclePtr to mitigate UAF

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#139]
Chrome [recently published]( https://security.googleblog.com/2022/09/use-after-freedom-miracleptr.html) their approach to mitigate UAF, and it does look decent and proper.

Do we want to use a similar approach?

**Comment by struct** [comment]
[Memory Tagging](https://github.com/struct/isoalloc/blob/master/MEMORY_TAGGING.md) in IsoAlloc is inspired by one of the Miracle Ptr proposals MTECheckedPtr. In order to build a BackupRefPtr on top of IsoAlloc you'd just need to implement a segment of memory that stored ref count meta data similar to how I did it in the [memory tagging support](https://github.com/struct/isoalloc/blob/master/src/iso_alloc_mem_tags.c). Shipping something like this with IsoAlloc would be pretty straight forward.

Another approach could also be considered where IsoAlloc has generic API's that allow you to store metadata per pointer which would allow you to build all kinds of smart pointer types, but in the general case it would be less performant than something that was tightly coupled to the allocator.

**Comment by struct** [comment]
BackupRefPtr [documentation](https://docs.google.com/document/d/1m0c63vXXLyGtIGBi9v6YFANum7-IRC3-dmiYBCWqkMk/edit)

**Comment by jvoisin** [comment]
> Shipping something like this with IsoAlloc would be pretty straight forward.

If such a primitive would be adopted, it would render the whole quarantine mechanism redundant I think.
