### ISSUE TITLE
Add guarded-memcopy support

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#86]
snmalloc has a [nice trick in its malloc implementation]( https://github.com/microsoft/snmalloc/blob/main/docs/security/GuardedMemcpy.md ), and it would be nice to borrow it :)

**Comment by struct** [comment]
This is a great idea. It will be tricky to implement in isoalloc because we first need to understand pointer provenance and that might require iterating internal data structures which require a lock. Requiring a lock for a memcpy is not great. But this could also be a forcing function for getting smarter about lockless iteration of these data structures or in ways that are safe for some scenarios. At a minimum would be useful when combined with sampling in release builds.

**Comment by struct** [comment]
Added in #107

**Comment by mjp41** [comment]
Awesome!!!

**Comment by jvoisin** [comment]
We forgot to implement `memmove`.
